const ProductListData = [
  {
    id: 0,
    label: "WomansWear",
    image: `${Url}/static/media/womenwear1.411a620948914b93900a.avif`,
    price: 1200,
    size: "M",
    status: "false",
    Name: "Dress",
    ProductOffer: "bestseller",
    to: "/womenColths",
  },
  {
    id: 1,
    label: "WomansWear",
    image: `${Url}/static/media/womenwear2.bab38f8580bb5d0f7808.avif`,
    price: 1060,
    size: "L",
    Name: "jens",
    status: "false",

    ProductOffer: "offer",
    to: "/womenColths",
  },
  {
    id: 2,
    label: "WomansWear",
    image: `${Url}/static/media/womenwear3.41c72cf2c2bf1f23cf1c.avif`,
    price: 1500,
    size: "XL",
    Name: "Casual",
    status: "false",
    ProductOffer: "bestseller",
    to: "/womenColths",
  },
  {
    id: 3,
    label: "WomansWear",
    image: `${Url}/static/media/womenwear5.4e3f7a9e944910ad5041.avif`,
    price: 1500,
    Name: "Western",
    size: "XS",
    status: "false",
    ProductOffer: "offer",
    to: "/womenColths",
  },
  {
    id: 4,
    label: "Menswear",
    image: `${Url}/static/media/menswear1.387d6f83942acdbc3213.avif`,
    price: 1050,
    Name: "mens tshirt",
    size: "S",
    status: "false",
    ProductOffer: "offer",
    to: "/MensColths",
  },
  {
    id: 5,
    label: "Menswear",
    image: `${Url}/static/media/menswear2.f12fedc940ef01cdcc5c.avif`,
    price: 1050,
    size: "XLL",
    Name: "Mens jens",
    status: "false",
    ProductOffer: "bestseller",
    to: "/mensColths",
  },
  {
    id: 6,
    label: "Menswear",
    image: `${Url}/static/media/menswear3.04f0fc54c1615dbbaa52.avif`,
    price: 1050,
    size: "M",
    status: "false",
    Name: "Mens shirt",
    to: "/mensColths",
  },
  {
    id: 7,
    label: "Menswear",
    image: `${Url}/static/media/menswear4.c53ead55a7011ea1fc32.avif`,
    price: 1050,
    size: "S",
    status: "false",
    Name: "casual  outfits",
    ProductOffer: "bestseller",
    to: "/mensColths",
  },
  {
    id: 8,
    label: "Kidswear",
    image: `${Url}/static/media/kidswear1.f79219d09f5b917448f1.avif`,
    price: 900,
    size: "1-3 YEAR",
    status: "false",
    Name: "skirts",
    to: "/Kidswear",
  },
  {
    id: 9,
    label: "Kidswear",
    image: `${Url}/static/media/kidswear2.1a3f0755aec16717d5d9.avif`,
    price: 900,
    size: "3-9 YEAR",
    status: "false",
    Name: " jumpsuit",
    ProductOffer: "bestseller",
    to: "/Kidswear",
  },
  {
    id: 10,
    label: "Kidswear",
    image: `${Url}/static/media/kidswear3.28b10b549c88381f83db.avif`,
    price: 900,
    size: "1-4 YEAR",
    status: "false",
    Name: "Froks",
    to: "/Kidswear",
  },
  {
    id: 11,
    label: "Kidswear",
    image: `${Url}/static/media/kidswear5.e2d8452c983b1fbbd5c4.avif`,
    price: 900,
    size: "10-12 YEAR",
    status: "false",
    Name: "Jens",
    ProductOffer: "bestseller",
    to: "/Kidswear",
  },
  {
    id: 12,
    label: "Footwear",
    image: `${Url}/static/media/footwear1.f8208d933c4fb2bfd9b9.avif`,
    price: 999,
    size: "7",
    status: "true",
    ProductOffer: "bestseller",
    Name: "Nike",
    to: "/footwear",
  },
  {
    id: 12,
    label: "Footwear",
    image: `${Url}/static/media/footwear2.1eb17709dc34b47e9903.avif`,
    price: 999,
    size: "5",
    status: "false",
    Name: "Puma",
    to: "/footwear",
  },
  {
    id: 12,
    label: "Footwear",
    image: `${Url}/static/media/footwear3.2ba02e4322bc7fdd721c.avif`,
    price: 999,
    size: "6",
    status: "true",
    Name: "Woodland",
    ProductOffer: "bestseller",
    to: "/footwear",
  },
  {
    id: 12,
    label: "Footwear",
    Name: "Adidas",
    image: `${Url}/static/media/footwear4.3a5b36d608bb08910bc6.avif`,
    price: 999,
    size: "9",
    status: "false",
    ProductOffer: "bestseller",
    to: "/footwear",
  },
  {
    id: 13,
    label: "Jewelary",
    image: `${Url}/static/media/cosmatics1.a319b0060e69eeb678f1.avif`,
    price: 2009,
    Name: "Eye shadow",
    status: "false",
    to: "/Jewelary",
  },
  {
    id: 14,
    label: "Jewelary",
    image: `${Url}/static/media/cosmatics2.89092d7d16333d5c4c68.avif`,
    price: 2009,
    status: "true",
    Name: "Lipsticks",
    ProductOffer: "bestseller",
    to: "/Jewelary",
  },
  {
    id: 15,
    label: "Jewelary",
    image: `${Url}/static/media/cosmatics3.d811403ddd8d3f602988.avif`,
    price: 2009,
    Name: "Skin Gel",
    status: "false",
    ProductOffer: "bestseller",
    to: "/Jewelary",
  },
  {
    id: 16,
    label: "Jewelary",
    image: `${Url}/static/media/cosmatics4.f7b4a6723d1a2f4fb989.avif`,
    price: 2009,
    Name: "Compact Powder",
    status: "false",
    ProductOffer: "bestseller",
    to: "/Jewelary",
  },
  {
    id: 17,
    label: "HomeAppliance",
    image: `${Url}/static/media/homeapplience1.168a0bd63d7c037d6517.avif`,
    price: 2009,
    Name: "Cutting Board",
    status: "true",
    to: "/HomeAppliance",
  },
  {
    image: 17,
    label: "HomeAppliance",
    image: `${Url}/static/media/homeapplience2.5a54356100147897cca5.avif`,
    price: 2009,
    Name: "Kitchen stuff",
    status: "false",
    ProductOffer: "offer",
    to: "/HomeAppliance",
  },
  {
    id: 17,
    label: "HomeAppliance",
    image: `${Url}/static/media/homeapplience3.537c81e3a6343298bb3c.avif`,
    price: 2009,
    Name: "Washing Machine",
    status: "false",
    ProductOffer: "offer",
    to: "/HomeAppliance",
  },
  {
    id: 17,
    label: "HomeAppliance",
    image: `${Url}/static/media/homeapplience4.30a2e091b6d388a46eb6.avif`,
    price: 2009,
    Name: "Toster",
    status: "true",
    ProductOffer: "offer",
    to: "/HomeAppliance",
  },
];
